AKIA4ASTEBHIVKS5ZEEODockerReact1-env-1sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t urajes123/docker-react -f Dockerfile.dev .
 
script:
  - docker run -e CI=true  urajes123/docker-react npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: docker-react1
  env: "DockerReact1-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-825881790929"
  bucket_path: "docker-react" 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
